fix(deeplink): Fix Deep Links (#461)
* fix deeplinks

* add unit test for deep link

* use zsh instead of bash

* Update function to get current format version

* fix most of the tests

* Fix last test

* reomve longer timeout

* fix linter error

 /home/runner/work/ahbesser/ahbesser/src/app/features/ahbs/components/format-version-select/format-version-select.component.spec.ts
Error:   4:48  error  'ngMocks' is defined but never used  @typescript-eslint/no-unused-vars

* add hint for upper threshold